[package]
name = "rlox"
version = "0.1.0"
authors = ["rindy1123 <genryusinbaou@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
substring = "1.4.5"
